# Generated by Django 3.0.8 on 2020-09-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('stoppage', models.TextField(help_text='Dont forget to add coordinates.')),
                ('bus_image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='From_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=60)),
                ('To', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_station', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cord',
            fields=[
                ('From_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bus.From_to')),
                ('coordinates', models.TextField(default=None, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default=None, max_length=200, null=True)),
                ('restaurant_link', models.CharField(default=None, max_length=200, null=True)),
                ('embed', models.TextField(default=None, null=True)),
                ('restaurant_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.Station')),
            ],
        ),
    ]
